import prisma from '../../config/prisma.js';
import { generateRef } from '../../utils/refGen.js';
import { logAudit } from '../../utils/auditLogger.js';
import { receiveStock } from '../../utils/stockEngine.js';
import { validateCreatePO, assertNoReceiptsYet } from './purchase.validation.js';
import { runSerialized } from '../../utils/mutex.js';

// ─── HELPERS ──────────────────────────────────────────────────────────────────

const formatPO = (po) => {
  const totalCost = (po.lines || []).reduce(
    (sum, l) => sum + Number(l.qty) * Number(l.unitCost),
    0
  );
  const totalReceived = (po.lines || []).reduce(
    (sum, l) => sum + Number(l.receivedQty),
    0
  );
  const totalOrdered = (po.lines || []).reduce(
    (sum, l) => sum + Number(l.qty),
    0
  );

  return {
    id: po.id,
    uid: po.uid,
    orderRef: po.orderRef,
    vendorId: po.vendorId,
    vendorName: po.vendor?.name ?? null,
    vendorEmail: po.vendor?.email ?? null,
    vendorPhone: po.vendor?.phone ?? null,
    userId: po.userId,
    createdByName: po.user?.name ?? null,
    tenantId: po.tenantId,
    salesOrderId: po.salesOrderId ?? null,
    salesOrderRef: po.salesOrder?.orderRef ?? null,
    status: po.status,
    orderDate: po.orderDate,
    expectedDeliveryDate: po.expectedDeliveryDate ?? null,
    receivedDate: po.receivedDate ?? null,
    notes: po.notes ?? null,
    isAutoGenerated: !!po.salesOrderId,
    totalCost,
    totalOrdered,
    totalReceived,
    createdAt: po.createdAt,
    updatedAt: po.updatedAt,
  };
};

const PO_INCLUDE_LIST = {
  vendor: true,
  user: { select: { name: true, role: true } },
  salesOrder: { select: { id: true, orderRef: true } },
  lines: { include: { product: { select: { id: true, name: true, sku: true } } } },
};

// ─── LIST ─────────────────────────────────────────────────────────────────────

export const getPurchaseOrders = async (query = {}, tenantId) => {
  const page = query.page ? parseInt(query.page, 10) : null;
  const limit = query.limit ? parseInt(query.limit, 10) : null;
  const search = query.search || "";

  const where = {
    tenantId,
    ...(query.status && query.status !== "all" && { status: query.status }),
    ...(query.vendorId && { vendorId: Number(query.vendorId) }),
    ...(query.autoGenerated === 'true' && { salesOrderId: { not: null } }),
    ...(query.autoGenerated === 'false' && { salesOrderId: null }),
    ...(search && {
      OR: [
        { orderRef: { contains: search, mode: "insensitive" } },
        { vendor: { name: { contains: search, mode: "insensitive" } } },
      ],
    }),
  };

  const totalItems = await prisma.purchaseOrder.count({ where });

  let orders;
  if (page && limit) {
    const skip = (page - 1) * limit;
    orders = await prisma.purchaseOrder.findMany({
      where,
      include: PO_INCLUDE_LIST,
      orderBy: { updatedAt: 'desc' },
      skip,
      take: limit,
    });
  } else {
    orders = await prisma.purchaseOrder.findMany({
      where,
      include: PO_INCLUDE_LIST,
      orderBy: { updatedAt: 'desc' },
    });
  }

  const formatted = orders.map(formatPO);

  if (page && limit) {
    return {
      data: formatted,
      pagination: {
        totalItems,
        totalPages: Math.ceil(totalItems / limit),
        currentPage: page,
        limit,
      },
    };
  }

  return formatted;
};

// ─── GET BY ID ────────────────────────────────────────────────────────────────

export const getPurchaseOrderById = async (id, tenantId) => {
  const po = await prisma.purchaseOrder.findFirst({
    where: { id, tenantId },
    include: {
      ...PO_INCLUDE_LIST,
      receipts: {
        include: {
          receivedBy: { select: { name: true, role: true } },
          lines: { include: { product: { select: { name: true, sku: true } } } },
        },
        orderBy: { receivedAt: 'asc' },
      },
    },
  });

  if (!po) throw { status: 404, message: 'Purchase Order not found' };

  const auditLogs = await prisma.auditLog.findMany({
    where: { purchaseOrderId: id, tenantId },
    include: { user: { select: { name: true, role: true } } },
    orderBy: { createdAt: 'asc' },
  });

  const formatted = formatPO(po);

  formatted.lines = (po.lines || []).map((l) => {
    const ordered = Number(l.qty);
    const received = Number(l.receivedQty);
    const remaining = Math.max(0, ordered - received);
    const progress = ordered > 0 ? Math.round((received / ordered) * 100) : 0;

    return {
      id: l.id,
      productId: l.productId,
      name: l.product?.name ?? null,
      sku: l.product?.sku ?? null,
      qty: ordered,
      receivedQty: received,
      remainingQty: remaining,
      unitCost: Number(l.unitCost),
      totalCost: ordered * Number(l.unitCost),
      receiptProgress: progress,
    };
  });

  formatted.receipts = (po.receipts || []).map((r) => ({
    id: r.id,
    receivedAt: r.receivedAt,
    receivedBy: r.receivedBy ? { name: r.receivedBy.name, role: r.receivedBy.role } : null,
    notes: r.notes ?? null,
    lines: r.lines.map((rl) => ({
      id: rl.id,
      productId: rl.productId,
      name: rl.product?.name ?? null,
      sku: rl.product?.sku ?? null,
      qty: Number(rl.qty),
    })),
  }));

  formatted.timeline = auditLogs.map((log) => ({
    id: log.id,
    action: log.action,
    description: log.description,
    createdAt: log.createdAt,
    user: log.user ? { name: log.user.name, role: log.user.role } : null,
  }));

  return formatted;
};

// ─── CREATE ───────────────────────────────────────────────────────────────────

export const createPurchaseOrder = async (data, userId, tenantId) => {
  await validateCreatePO(data, tenantId);

  const { vendorId, notes, lines, expectedDeliveryDate } = data;

  let orderRefVal = null;
  let createdPoId = null;

  const po = await runSerialized(`PO_${tenantId}`, () => prisma.$transaction(async (tx) => {
    const orderRef = await generateRef('PO', tenantId, tx);
    orderRefVal = orderRef;

    const created = await tx.purchaseOrder.create({
      data: {
        orderRef,
        vendorId: Number(vendorId),
        userId,
        tenantId,
        notes: notes?.trim() || null,
        expectedDeliveryDate: expectedDeliveryDate ? new Date(expectedDeliveryDate) : null,
        status: 'DRAFT',
        lines: {
          create: lines.map((l) => ({
            productId: Number(l.productId),
            qty: Number(l.qty),
            unitCost: Number(l.unitCost),
          })),
        },
      },
      include: PO_INCLUDE_LIST,
    });
    createdPoId = created.id;

    return created;
  }, { timeout: 10000 }));

  try {
    await logAudit({
      tenantId, userId, action: 'PO_CREATED',
      entityType: 'PurchaseOrder', entityId: createdPoId,
      entityRef: orderRefVal,
      description: `Purchase Order ${orderRefVal} created with ${lines.length} line(s).`,
      purchaseOrderId: createdPoId,
      metadata: { vendorId, lineCount: lines.length },
    });
  } catch (auditErr) {
    console.error("Non-blocking audit log creation failed:", auditErr);
  }

  return formatPO(po);
};

// ─── CONFIRM ──────────────────────────────────────────────────────────────────

export const confirmPurchaseOrder = async (id, userId, tenantId) => {
  const po = await prisma.purchaseOrder.findFirst({ where: { id, tenantId }, include: { lines: true } });
  if (!po) throw { status: 404, message: 'Purchase Order not found' };

  if (po.status !== 'DRAFT') {
    throw { status: 400, message: `Cannot confirm a Purchase Order in "${po.status}" status. Only DRAFT orders can be confirmed.` };
  }
  if (!po.lines || po.lines.length === 0) {
    throw { status: 400, message: 'Cannot confirm a Purchase Order with no line items.' };
  }

  const updated = await prisma.$transaction(async (tx) => {
    return tx.purchaseOrder.update({
      where: { id },
      data: { status: 'SENT' },
      include: PO_INCLUDE_LIST,
    });
  }, { timeout: 10000 });

  try {
    await logAudit({
      tenantId, userId, action: 'PO_SENT',
      entityType: 'PurchaseOrder', entityId: id,
      entityRef: po.orderRef,
      description: `Purchase Order ${po.orderRef} confirmed and sent to vendor.`,
      purchaseOrderId: id,
    });
  } catch (auditErr) {
    console.error("Non-blocking audit log creation failed:", auditErr);
  }

  return formatPO(updated);
};

// ─── RECEIVE GOODS ────────────────────────────────────────────────────────────

export const receiveGoods = async (id, receiptsPayload, userId, tenantId) => {
  const po = await prisma.purchaseOrder.findFirst({
    where: { id, tenantId },
    include: { lines: true },
  });
  if (!po) throw { status: 404, message: 'Purchase Order not found' };

  if (!['SENT', 'PARTIALLY_RECEIVED'].includes(po.status)) {
    throw {
      status: 400,
      message: `Cannot receive goods for a Purchase Order in "${po.status}" status. Only CONFIRMED or PARTIALLY_RECEIVED orders accept receipt.`,
    };
  }

  const { receipts, notes } = receiptsPayload;
  if (!receipts || !Array.isArray(receipts) || receipts.length === 0) {
    throw { status: 400, message: 'Receipt must include at least one line.' };
  }

  // Build a map of lineId → line for validation
  const lineMap = new Map(po.lines.map((l) => [l.id, l]));

  for (const r of receipts) {
    const line = lineMap.get(Number(r.lineId));
    if (!line) throw { status: 400, message: `Line ID ${r.lineId} does not belong to this Purchase Order.` };

    const receivedQty = Number(r.receivedQty);
    if (isNaN(receivedQty) || receivedQty <= 0) {
      throw { status: 400, message: `Received quantity for line ${r.lineId} must be a positive number.` };
    }

    const remaining = Number(line.qty) - Number(line.receivedQty);
    if (receivedQty > remaining) {
      throw {
        status: 400,
        message: `Cannot receive ${receivedQty} units for line ${r.lineId}. Only ${remaining} unit(s) remaining.`,
      };
    }
  }

  let auditActionVal = null;
  let receiptIdVal = null;
  let newStatusVal = null;

  const result = await prisma.$transaction(async (tx) => {
    // 1. Create PurchaseReceipt record
    const receipt = await tx.purchaseReceipt.create({
      data: {
        tenantId,
        purchaseOrderId: id,
        receivedById: userId,
        notes: notes?.trim() || null,
        lines: {
          create: receipts.map((r) => {
            const line = lineMap.get(Number(r.lineId));
            return {
              purchaseOrderLineId: Number(r.lineId),
              productId: line.productId,
              qty: Number(r.receivedQty),
            };
          }),
        },
      },
    });
    receiptIdVal = receipt.id;

    // 2. Update each PO line receivedQty + stock
    for (const r of receipts) {
      const line = lineMap.get(Number(r.lineId));
      const receivedQty = Number(r.receivedQty);

      await tx.purchaseOrderLine.update({
        where: { id: line.id },
        data: { receivedQty: { increment: receivedQty } },
      });

      await receiveStock(line.productId, receivedQty, Number(line.unitCost), id, tenantId, null, tx);
    }

    // 3. Re-fetch lines to compute new status
    const freshLines = await tx.purchaseOrderLine.findMany({ where: { purchaseOrderId: id } });
    const allReceived = freshLines.every((l) => Number(l.receivedQty) >= Number(l.qty));
    const anyReceived = freshLines.some((l) => Number(l.receivedQty) > 0);

    let newStatus = po.status;
    let receivedDate = null;
    if (allReceived) {
      newStatus = 'RECEIVED';
      receivedDate = new Date();
    } else if (anyReceived) {
      newStatus = 'PARTIALLY_RECEIVED';
    }
    newStatusVal = newStatus;
    auditActionVal = newStatus === 'RECEIVED' ? 'PO_RECEIVED' : 'PO_PARTIALLY_RECEIVED';

    const updatedPO = await tx.purchaseOrder.update({
      where: { id },
      data: {
        status: newStatus,
        ...(receivedDate && { receivedDate }),
      },
      include: PO_INCLUDE_LIST,
    });

    return updatedPO;
  }, { timeout: 10000 });

  try {
    const totalReceived = receipts.reduce((sum, r) => sum + Number(r.receivedQty), 0);
    await logAudit({
      tenantId, userId, action: auditActionVal,
      entityType: 'PurchaseOrder', entityId: id,
      entityRef: po.orderRef,
      description: `Received ${totalReceived} unit(s) on Purchase Order ${po.orderRef}. Status → ${newStatusVal}.`,
      purchaseOrderId: id,
      metadata: { receiptId: receiptIdVal, lines: receipts, newStatus: newStatusVal },
    });
  } catch (auditErr) {
    console.error("Non-blocking audit log creation failed:", auditErr);
  }

  return formatPO(result);
};

// ─── CANCEL ───────────────────────────────────────────────────────────────────

export const cancelPurchaseOrder = async (id, userId, tenantId) => {
  const po = await prisma.purchaseOrder.findFirst({ where: { id, tenantId } });
  if (!po) throw { status: 404, message: 'Purchase Order not found' };

  if (!['DRAFT', 'SENT'].includes(po.status)) {
    throw { status: 400, message: `Cannot cancel a Purchase Order in "${po.status}" status.` };
  }

  // Enforce edit lock — cannot cancel if receipts already exist
  await assertNoReceiptsYet(id, tenantId);

  const updated = await prisma.$transaction(async (tx) => {
    return tx.purchaseOrder.update({
      where: { id },
      data: { status: 'CANCELLED' },
      include: PO_INCLUDE_LIST,
    });
  }, { timeout: 10000 });

  try {
    await logAudit({
      tenantId, userId, action: 'PO_CANCELLED',
      entityType: 'PurchaseOrder', entityId: id,
      entityRef: po.orderRef,
      description: `Purchase Order ${po.orderRef} cancelled.`,
      purchaseOrderId: id,
    });
  } catch (auditErr) {
    console.error("Non-blocking audit log creation failed:", auditErr);
  }

  return formatPO(updated);
};
