import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { getPurchaseOrders } from '../../api/purchase.api';
import { useAuthStore } from '../../store/authStore';
import Button from '../../components/ui/Button';
import { LayoutList, FileText, CheckCircle2, Truck, XCircle, Zap, User, Layers, Package } from 'lucide-react';

const STATUS_CONFIG = {
  DRAFT: { label: 'Draft', bg: 'rgba(148,163,184,0.15)', color: '#94A3B8', border: 'rgba(148,163,184,0.25)' },
  SENT: { label: 'Confirmed', bg: 'rgba(59,130,246,0.12)', color: '#60A5FA', border: 'rgba(59,130,246,0.25)' },
  PARTIALLY_RECEIVED: { label: 'Partially Received', bg: 'rgba(251,146,60,0.12)', color: '#FB923C', border: 'rgba(251,146,60,0.25)' },
  RECEIVED: { label: 'Fully Received', bg: 'rgba(34,197,94,0.12)', color: '#4ADE80', border: 'rgba(34,197,94,0.25)' },
  CANCELLED: { label: 'Cancelled', bg: 'rgba(239,68,68,0.1)', color: '#F87171', border: 'rgba(239,68,68,0.2)' },
};

const StatusBadge = ({ status }) => {
  const cfg = STATUS_CONFIG[status] || { label: status, bg: 'rgba(148,163,184,0.15)', color: '#94A3B8', border: 'rgba(148,163,184,0.25)' };
  return (
    <span style={{
      display: 'inline-block',
      padding: '3px 10px',
      borderRadius: '20px',
      fontSize: '11px',
      fontWeight: 600,
      letterSpacing: '0.03em',
      background: cfg.bg,
      color: cfg.color,
      border: `1px solid ${cfg.border}`,
    }}>
      {cfg.label}
    </span>
  );
};

const PurchaseListPage = () => {
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const userRole = user?.role;

  const [statusFilter, setStatusFilter] = useState('');
  const [autoFilter, setAutoFilter] = useState('');

  const canCreate = ['ADMIN', 'PURCHASE_USER'].includes(userRole);

  const { data: orders = [], isLoading } = useQuery({
    queryKey: ['purchaseOrders', statusFilter, autoFilter],
    queryFn: () => getPurchaseOrders({
      ...(statusFilter && { status: statusFilter }),
      ...(autoFilter && { autoGenerated: autoFilter }),
    }),
  });

  const chipStyle = (active, color) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 12px',
    borderRadius: '9999px',
    border: active ? `1.5px solid ${color}` : '1.5px solid rgba(0,0,0,0.08)',
    background: active ? `${color}18` : 'rgba(0,0,0,0.03)',
    color: active ? color : 'var(--text-secondary)',
    fontSize: '12.5px',
    fontWeight: active ? 600 : 500,
    cursor: 'pointer',
    transition: 'all 0.18s ease',
    userSelect: 'none',
    whiteSpace: 'nowrap',
  });

  const hasActiveFilters = statusFilter !== '' || autoFilter !== '';

  return (
    <div className="animate-fade-in" style={{ fontFamily: 'var(--font-family)' }}>
      {/* Page Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' }}>
        <div>
          <h2 style={{ fontSize: '20px', fontWeight: 700, color: 'var(--text-primary)', margin: 0 }}>
            Purchase Orders
          </h2>
          <p style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px', marginBottom: 0 }}>
            Manage vendor procurement, goods receipts, and inventory replenishment.
          </p>
        </div>
        {canCreate && (
          <Button
            id="btn-create-purchase-order"
            onClick={() => navigate('/purchase/new')}
            style={{ background: 'linear-gradient(135deg, #6366F1, #8B5CF6)', flexShrink: 0 }}
          >
            + New Purchase Order
          </Button>
        )}
      </div>

      {/* Main List Table & Filters */}
      <div className="glass-card" style={{ padding: '24px' }}>
        {/* ── Filter Chips ── */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', marginBottom: '20px', paddingBottom: '16px', borderBottom: '1px solid var(--border)' }}>
          {/* Status Filters */}
          <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '8px' }}>
            <span style={{ fontSize: '11px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginRight: '8px', minWidth: '60px' }}>Status</span>

            <button style={chipStyle(statusFilter === '', '#6B7280')} onClick={() => setStatusFilter('')}>
              <LayoutList size={13} strokeWidth={2.5} />
              All
            </button>
            <button style={chipStyle(statusFilter === 'DRAFT', '#94A3B8')} onClick={() => setStatusFilter('DRAFT')}>
              <FileText size={13} strokeWidth={2.5} />
              Draft
            </button>
            <button style={chipStyle(statusFilter === 'SENT', '#3B82F6')} onClick={() => setStatusFilter('SENT')}>
              <CheckCircle2 size={13} strokeWidth={2.5} />
              Confirmed
            </button>
            <button style={chipStyle(statusFilter === 'PARTIALLY_RECEIVED', '#F59E0B')} onClick={() => setStatusFilter('PARTIALLY_RECEIVED')}>
              <Truck size={13} strokeWidth={2.5} style={{ transform: 'scaleX(-1)' }} />
              Partially Received
            </button>
            <button style={chipStyle(statusFilter === 'RECEIVED', '#10B981')} onClick={() => setStatusFilter('RECEIVED')}>
              <CheckCircle2 size={13} strokeWidth={2.5} />
              Fully Received
            </button>
            <button style={chipStyle(statusFilter === 'CANCELLED', '#EF4444')} onClick={() => setStatusFilter('CANCELLED')}>
              <XCircle size={13} strokeWidth={2.5} />
              Cancelled
            </button>
          </div>

          {/* Origin Filters */}
          <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '8px' }}>
            <span style={{ fontSize: '11px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginRight: '8px', minWidth: '60px' }}>Origin</span>

            <button style={chipStyle(autoFilter === '', '#6B7280')} onClick={() => setAutoFilter('')}>
              <Layers size={13} strokeWidth={2.5} />
              All Origins
            </button>
            <button style={chipStyle(autoFilter === 'true', '#818CF8')} onClick={() => setAutoFilter('true')}>
              <Zap size={13} strokeWidth={2.5} />
              Auto-Generated (MTO)
            </button>
            <button style={chipStyle(autoFilter === 'false', '#94A3B8')} onClick={() => setAutoFilter('false')}>
              <User size={13} strokeWidth={2.5} />
              Manual
            </button>

            {/* Clear filters */}
            {hasActiveFilters && (
              <button
                onClick={() => {
                  setStatusFilter('');
                  setAutoFilter('');
                }}
                style={{
                  marginLeft: 'auto',
                  fontSize: '12px',
                  color: '#EF4444',
                  background: 'rgba(239,68,68,0.07)',
                  border: '1.5px solid rgba(239,68,68,0.25)',
                  borderRadius: '9999px',
                  padding: '5px 12px',
                  cursor: 'pointer',
                  fontWeight: 600,
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '5px'
                }}
              >
                ✕ Clear filters
              </button>
            )}
          </div>
        </div>

        {isLoading ? (
          <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-muted)' }}>
            Loading Purchase Orders…
          </div>
        ) : orders.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px 40px', color: 'var(--text-muted)' }}>
            <Package size={40} strokeWidth={1.5} style={{ color: 'var(--text-muted)', marginBottom: '12px', display: 'inline-block' }} />
            <p style={{ marginTop: '12px', fontSize: '14px' }}>
              {hasActiveFilters ? 'No purchase orders match the selected filters.' : 'No purchase orders found.'}
            </p>
            {hasActiveFilters ? (
              <button
                onClick={() => {
                  setStatusFilter('');
                  setAutoFilter('');
                }}
                style={{ marginTop: '12px', background: 'transparent', border: '1px solid var(--border)', color: 'var(--text-secondary)', borderRadius: '8px', padding: '8px 18px', cursor: 'pointer', fontSize: '13px' }}
              >
                Clear Filters
              </button>
            ) : (
              canCreate && (
                <button
                  onClick={() => navigate('/purchase/new')}
                  style={{ marginTop: '12px', background: 'transparent', border: '1px solid var(--border)', color: 'var(--text-secondary)', borderRadius: '8px', padding: '8px 18px', cursor: 'pointer', fontSize: '13px' }}
                >
                  Create your first Purchase Order
                </button>
              )
            )}
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table className="erp-table">
              <thead>
                <tr>
                  <th>Reference</th>
                  <th>Vendor</th>
                  <th>Origin</th>
                  <th>Order Date</th>
                  <th>Expected Delivery</th>
                  <th style={{ textAlign: 'right' }}>Total Cost</th>
                  <th>Status</th>
                  <th style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {orders.map((o) => (
                  <tr key={o.id}>
                    <td style={{ fontWeight: 600, color: '#818CF8' }}>{o.orderRef}</td>
                    <td>{o.vendorName}</td>
                    <td>
                      {o.isAutoGenerated ? (
                        <span style={{
                          display: 'inline-flex', alignItems: 'center', gap: '4px',
                          background: 'rgba(99,102,241,0.1)', color: '#818CF8',
                          border: '1px solid rgba(99,102,241,0.2)',
                          borderRadius: '20px', padding: '2px 8px', fontSize: '11px', fontWeight: 600,
                        }}>
                          <Zap size={11} strokeWidth={2.5} /> MTO
                        </span>
                      ) : (
                        <span style={{ color: 'var(--text-muted)', fontSize: '12px' }}>Manual</span>
                      )}
                    </td>
                    <td>{new Date(o.orderDate).toLocaleDateString()}</td>
                    <td>{o.expectedDeliveryDate ? new Date(o.expectedDeliveryDate).toLocaleDateString() : '—'}</td>
                    <td style={{ textAlign: 'right', fontWeight: 600 }}>
                      ₹{(o.totalCost || 0).toFixed(2)}
                    </td>
                    <td><StatusBadge status={o.status} /></td>
                    <td style={{ textAlign: 'right' }}>
                      <button
                        onClick={() => navigate(`/purchase/${o.id}`)}
                        style={{
                          background: 'rgba(255,255,255,0.05)',
                          border: '1px solid var(--border)',
                          color: 'var(--text-primary)',
                          cursor: 'pointer',
                          padding: '4px 12px',
                          borderRadius: '6px',
                          fontSize: '12px',
                        }}
                      >
                        View
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {orders.length > 0 && (
              <div style={{ paddingTop: '12px', fontSize: '12px', color: 'var(--text-muted)' }}>
                Showing {orders.length} purchase order{orders.length !== 1 ? 's' : ''}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default PurchaseListPage;
