import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { getPurchaseOrders } from '../../api/purchase.api';
import { useAuthStore } from '../../store/authStore';
import Button from '../../components/ui/Button';

const STATUS_CONFIG = {
  DRAFT: { label: 'Draft', bg: 'rgba(148,163,184,0.15)', color: '#94A3B8', border: 'rgba(148,163,184,0.25)' },
  SENT: { label: 'Confirmed', bg: 'rgba(59,130,246,0.12)', color: '#60A5FA', border: 'rgba(59,130,246,0.25)' },
  PARTIALLY_RECEIVED: { label: 'Partially Received', bg: 'rgba(251,146,60,0.12)', color: '#FB923C', border: 'rgba(251,146,60,0.25)' },
  RECEIVED: { label: 'Fully Received', bg: 'rgba(34,197,94,0.12)', color: '#4ADE80', border: 'rgba(34,197,94,0.25)' },
  CANCELLED: { label: 'Cancelled', bg: 'rgba(239,68,68,0.1)', color: '#F87171', border: 'rgba(239,68,68,0.2)' },
};

const StatusBadge = ({ status }) => {
  const cfg = STATUS_CONFIG[status] || { label: status, bg: 'rgba(148,163,184,0.15)', color: '#94A3B8', border: 'rgba(148,163,184,0.25)' };
  return (
    <span style={{
      display: 'inline-block',
      padding: '3px 10px',
      borderRadius: '20px',
      fontSize: '11px',
      fontWeight: 600,
      letterSpacing: '0.03em',
      background: cfg.bg,
      color: cfg.color,
      border: `1px solid ${cfg.border}`,
    }}>
      {cfg.label}
    </span>
  );
};

const PurchaseListPage = () => {
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const userRole = user?.role;

  const [statusFilter, setStatusFilter] = useState('');
  const [autoFilter, setAutoFilter] = useState('');

  const canCreate = ['ADMIN', 'PURCHASE_USER'].includes(userRole);

  const { data: orders = [], isLoading } = useQuery({
    queryKey: ['purchaseOrders', statusFilter, autoFilter],
    queryFn: () => getPurchaseOrders({
      ...(statusFilter && { status: statusFilter }),
      ...(autoFilter && { autoGenerated: autoFilter }),
    }),
  });

  const filterSelectStyle = {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    color: 'var(--text-primary)',
    borderRadius: '8px',
    padding: '6px 12px',
    fontSize: '13px',
    cursor: 'pointer',
    outline: 'none',
  };

  return (
    <div className="animate-fade-in" style={{ fontFamily: 'var(--font-family)' }}>
      {/* Page Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' }}>
        <div>
          <h2 style={{ fontSize: '20px', fontWeight: 700, color: 'var(--text-primary)', margin: 0 }}>
            Purchase Orders
          </h2>
          <p style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px', marginBottom: 0 }}>
            Manage vendor procurement, goods receipts, and inventory replenishment.
          </p>
        </div>
        {canCreate && (
          <Button
            id="btn-create-purchase-order"
            onClick={() => navigate('/purchase/new')}
            style={{ background: 'linear-gradient(135deg, #6366F1, #8B5CF6)', flexShrink: 0 }}
          >
            + New Purchase Order
          </Button>
        )}
      </div>

      {/* Filters */}
      <div style={{ display: 'flex', gap: '10px', marginBottom: '16px', flexWrap: 'wrap' }}>
        <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} style={filterSelectStyle}>
          <option value="">All Statuses</option>
          <option value="DRAFT">Draft</option>
          <option value="SENT">Confirmed</option>
          <option value="PARTIALLY_RECEIVED">Partially Received</option>
          <option value="RECEIVED">Fully Received</option>
          <option value="CANCELLED">Cancelled</option>
        </select>
        <select value={autoFilter} onChange={(e) => setAutoFilter(e.target.value)} style={filterSelectStyle}>
          <option value="">All Origins</option>
          <option value="true">Auto-Generated (MTO)</option>
          <option value="false">Manual</option>
        </select>
      </div>

      {/* Table */}
      <div className="glass-card" style={{ padding: '24px' }}>
        {isLoading ? (
          <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-muted)' }}>
            Loading Purchase Orders…
          </div>
        ) : orders.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px 40px', color: 'var(--text-muted)' }}>
            <span style={{ fontSize: '32px' }}>📦</span>
            <p style={{ marginTop: '12px', fontSize: '14px' }}>No purchase orders found.</p>
            {canCreate && (
              <button
                onClick={() => navigate('/purchase/new')}
                style={{ marginTop: '12px', background: 'transparent', border: '1px solid var(--border)', color: 'var(--text-secondary)', borderRadius: '8px', padding: '8px 18px', cursor: 'pointer', fontSize: '13px' }}
              >
                Create your first Purchase Order
              </button>
            )}
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table className="erp-table">
              <thead>
                <tr>
                  <th>Reference</th>
                  <th>Vendor</th>
                  <th>Origin</th>
                  <th>Order Date</th>
                  <th>Expected Delivery</th>
                  <th style={{ textAlign: 'right' }}>Total Cost</th>
                  <th>Status</th>
                  <th style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {orders.map((o) => (
                  <tr key={o.id}>
                    <td style={{ fontWeight: 600, color: '#818CF8' }}>{o.orderRef}</td>
                    <td>{o.vendorName}</td>
                    <td>
                      {o.isAutoGenerated ? (
                        <span style={{
                          display: 'inline-flex', alignItems: 'center', gap: '4px',
                          background: 'rgba(99,102,241,0.1)', color: '#818CF8',
                          border: '1px solid rgba(99,102,241,0.2)',
                          borderRadius: '20px', padding: '2px 8px', fontSize: '11px', fontWeight: 600,
                        }}>
                          ⚡ MTO
                        </span>
                      ) : (
                        <span style={{ color: 'var(--text-muted)', fontSize: '12px' }}>Manual</span>
                      )}
                    </td>
                    <td>{new Date(o.orderDate).toLocaleDateString()}</td>
                    <td>{o.expectedDeliveryDate ? new Date(o.expectedDeliveryDate).toLocaleDateString() : '—'}</td>
                    <td style={{ textAlign: 'right', fontWeight: 600 }}>
                      ₹{(o.totalCost || 0).toFixed(2)}
                    </td>
                    <td><StatusBadge status={o.status} /></td>
                    <td style={{ textAlign: 'right' }}>
                      <button
                        onClick={() => navigate(`/purchase/${o.id}`)}
                        style={{
                          background: 'rgba(255,255,255,0.05)',
                          border: '1px solid var(--border)',
                          color: 'var(--text-primary)',
                          cursor: 'pointer',
                          padding: '4px 12px',
                          borderRadius: '6px',
                          fontSize: '12px',
                        }}
                      >
                        View
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default PurchaseListPage;
