import React, { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { getPurchaseOrders } from '../../api/purchase.api';
import { useAuthStore } from '../../store/authStore';
import Button from '../../components/ui/Button';
import { LayoutList, FileText, CheckCircle2, Truck, XCircle, Zap, User, Layers, Package } from 'lucide-react';
import Loader from '../../components/ui/Loader';
import Pagination from '../../components/ui/Pagination';

const STATUS_CONFIG = {
  DRAFT: { label: 'Draft', bg: 'rgba(148,163,184,0.15)', color: '#94A3B8', border: 'rgba(148,163,184,0.25)' },
  SENT: { label: 'Confirmed', bg: 'rgba(255,84,14,0.08)', color: '#FF8A58', border: 'rgba(255,84,14,0.25)' },
  PARTIALLY_RECEIVED: { label: 'Partially Received', bg: 'rgba(251,146,60,0.12)', color: '#FB923C', border: 'rgba(251,146,60,0.25)' },
  RECEIVED: { label: 'Fully Received', bg: 'rgba(34,197,94,0.12)', color: '#4ADE80', border: 'rgba(34,197,94,0.25)' },
  CANCELLED: { label: 'Cancelled', bg: 'rgba(239,68,68,0.1)', color: '#F87171', border: 'rgba(239,68,68,0.2)' },
};

const StatusBadge = ({ status }) => {
  const cfg = STATUS_CONFIG[status] || { label: status, bg: 'rgba(148,163,184,0.15)', color: '#94A3B8', border: 'rgba(148,163,184,0.25)' };
  return (
    <span style={{
      display: 'inline-block',
      padding: '3px 10px',
      borderRadius: '20px',
      fontSize: '11px',
      fontWeight: 600,
      letterSpacing: '0.03em',
      background: cfg.bg,
      color: cfg.color,
      border: `1px solid ${cfg.border}`,
    }}>
      {cfg.label}
    </span>
  );
};

const PurchaseListPage = () => {
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const userRole = user?.role;

  const [searchParams, setSearchParams] = useSearchParams();
  const page = parseInt(searchParams.get('page') || '1', 10);
  const statusFilter = searchParams.get('status') || '';
  const autoFilter = searchParams.get('autoGenerated') || '';

  const [searchQuery, setSearchQuery] = useState('');

  const canCreate = ['ADMIN', 'PURCHASE_USER'].includes(userRole);

  const { data: responseData, isLoading } = useQuery({
    queryKey: ['purchaseOrders', page, statusFilter, autoFilter, searchQuery],
    queryFn: () => getPurchaseOrders({
      page,
      limit: 10,
      ...(statusFilter && { status: statusFilter }),
      ...(autoFilter && { autoGenerated: autoFilter }),
      search: searchQuery,
    }),
  });

  const orders = responseData?.data || [];
  const pagination = responseData?.pagination;

  const chipStyle = (active, color) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 12px',
    borderRadius: '9999px',
    border: active ? `1.5px solid ${color}` : '1.5px solid rgba(0,0,0,0.08)',
    background: active ? `${color}18` : 'rgba(0,0,0,0.03)',
    color: active ? color : 'var(--text-secondary)',
    fontSize: '12.5px',
    fontWeight: active ? 600 : 500,
    cursor: 'pointer',
    transition: 'all 0.18s ease',
    userSelect: 'none',
    whiteSpace: 'nowrap',
  });

  const hasActiveFilters = statusFilter !== '' || autoFilter !== '';

  const handlePageChange = (newPage) => {
    const params = new URLSearchParams(window.location.search);
    params.set('page', newPage);
    setSearchParams(params);
  };

  const handleStatusFilterChange = (newStatus) => {
    const params = new URLSearchParams(window.location.search);
    if (newStatus) params.set('status', newStatus);
    else params.delete('status');
    params.set('page', '1');
    setSearchParams(params);
  };

  const handleAutoFilterChange = (newAuto) => {
    const params = new URLSearchParams(window.location.search);
    if (newAuto) params.set('autoGenerated', newAuto);
    else params.delete('autoGenerated');
    params.set('page', '1');
    setSearchParams(params);
  };

  const handleSearchChange = (val) => {
    setSearchQuery(val);
    const params = new URLSearchParams(window.location.search);
    params.set('page', '1');
    setSearchParams(params);
  };

  return (
    <div className="animate-fade-in" style={{ fontFamily: 'var(--font-family)' }}>
      {/* Page Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' }}>
        <div>
          <h2 style={{ fontSize: '20px', fontWeight: 700, color: 'var(--text-primary)', margin: 0 }}>
            Purchase Orders
          </h2>
          <p style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px', marginBottom: 0 }}>
            Manage vendor procurement, goods receipts, and inventory replenishment.
          </p>
        </div>
        {canCreate && (
          <Button
            id="btn-create-purchase-order"
            onClick={() => navigate('/purchase/new')}
            style={{ flexShrink: 0 }}
          >
            + New Purchase Order
          </Button>
        )}
      </div>

      {/* Main List Table & Filters */}
      <div className="glass-card" style={{ padding: '24px' }}>
        {/* Search Input Bar */}
        <div style={{ marginBottom: '20px', display: 'flex', gap: '12px', alignItems: 'center' }}>
          <input
            type="text"
            placeholder="Search by order reference or vendor name..."
            value={searchQuery}
            onChange={(e) => handleSearchChange(e.target.value)}
            style={{
              width: '100%',
              maxWidth: '400px',
              padding: '10px 14px',
              borderRadius: '8px',
              border: '1px solid var(--border)',
              background: 'var(--bg-card)',
              color: 'var(--text-primary)',
              fontSize: '13.5px',
              outline: 'none',
              transition: 'all 0.15s ease',
            }}
            onFocus={(e) => {
              e.currentTarget.style.borderColor = '#FF540E';
              e.currentTarget.style.boxShadow = '0 0 0 3px rgba(255,84,14,0.12)';
            }}
            onBlur={(e) => {
              e.currentTarget.style.borderColor = 'var(--border)';
              e.currentTarget.style.boxShadow = 'none';
            }}
          />
          {searchQuery && (
            <button
              onClick={() => handleSearchChange('')}
              style={{
                background: 'transparent',
                border: 'none',
                color: '#EF4444',
                fontSize: '13px',
                fontWeight: 600,
                cursor: 'pointer',
              }}
            >
              Clear Search
            </button>
          )}
        </div>

        {/* ── Filter Chips ── */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', marginBottom: '20px', paddingBottom: '16px', borderBottom: '1px solid var(--border)' }}>
          {/* Status Filters */}
          <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '8px' }}>
            <span style={{ fontSize: '11px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginRight: '8px', minWidth: '60px' }}>Status</span>

            <button style={chipStyle(statusFilter === '', '#6B7280')} onClick={() => handleStatusFilterChange('')}>
              <LayoutList size={13} strokeWidth={2.5} />
              All
            </button>
            <button style={chipStyle(statusFilter === 'DRAFT', '#94A3B8')} onClick={() => handleStatusFilterChange('DRAFT')}>
              <FileText size={13} strokeWidth={2.5} />
              Draft
            </button>
            <button style={chipStyle(statusFilter === 'SENT', '#3B82F6')} onClick={() => handleStatusFilterChange('SENT')}>
              <CheckCircle2 size={13} strokeWidth={2.5} />
              Confirmed
            </button>
            <button style={chipStyle(statusFilter === 'PARTIALLY_RECEIVED', '#F59E0B')} onClick={() => handleStatusFilterChange('PARTIALLY_RECEIVED')}>
              <Truck size={13} strokeWidth={2.5} style={{ transform: 'scaleX(-1)' }} />
              Partially Received
            </button>
            <button style={chipStyle(statusFilter === 'RECEIVED', '#10B981')} onClick={() => handleStatusFilterChange('RECEIVED')}>
              <CheckCircle2 size={13} strokeWidth={2.5} />
              Fully Received
            </button>
            <button style={chipStyle(statusFilter === 'CANCELLED', '#EF4444')} onClick={() => handleStatusFilterChange('CANCELLED')}>
              <XCircle size={13} strokeWidth={2.5} />
              Cancelled
            </button>
          </div>

          {/* Origin Filters */}
          <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '8px' }}>
            <span style={{ fontSize: '11px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginRight: '8px', minWidth: '60px' }}>Origin</span>

            <button style={chipStyle(autoFilter === '', '#6B7280')} onClick={() => handleAutoFilterChange('')}>
              <Layers size={13} strokeWidth={2.5} />
              All Origins
            </button>
            <button style={chipStyle(autoFilter === 'true', '#FF540E')} onClick={() => handleAutoFilterChange('true')}>
              <Zap size={13} strokeWidth={2.5} />
              Auto-Generated (MTO)
            </button>
            <button style={chipStyle(autoFilter === 'false', '#94A3B8')} onClick={() => handleAutoFilterChange('false')}>
              <User size={13} strokeWidth={2.5} />
              Manual
            </button>

            {/* Clear filters */}
            {hasActiveFilters && (
              <button
                onClick={() => {
                  handleStatusFilterChange('');
                  handleAutoFilterChange('');
                }}
                style={{
                  marginLeft: 'auto',
                  fontSize: '12px',
                  color: '#EF4444',
                  background: 'rgba(239,68,68,0.07)',
                  border: '1.5px solid rgba(239,68,68,0.25)',
                  borderRadius: '9999px',
                  padding: '5px 12px',
                  cursor: 'pointer',
                  fontWeight: 600,
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '5px'
                }}
              >
                ✕ Clear filters
              </button>
            )}
          </div>
        </div>

        {isLoading ? (
          <Loader padding="40px 0" size={28} />
        ) : orders.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px 40px', color: 'var(--text-muted)' }}>
            <Package size={40} strokeWidth={1.5} style={{ color: 'var(--text-muted)', marginBottom: '12px', display: 'inline-block' }} />
            <p style={{ marginTop: '12px', fontSize: '14px' }}>
              {hasActiveFilters ? 'No purchase orders match the selected filters.' : 'No purchase orders found.'}
            </p>
            {hasActiveFilters ? (
              <button
                onClick={() => {
                  handleStatusFilterChange('');
                  handleAutoFilterChange('');
                }}
                style={{ marginTop: '12px', background: 'transparent', border: '1px solid var(--border)', color: 'var(--text-secondary)', borderRadius: '8px', padding: '8px 18px', cursor: 'pointer', fontSize: '13px' }}
              >
                Clear Filters
              </button>
            ) : (
              canCreate && (
                <button
                  onClick={() => navigate('/purchase/new')}
                  style={{ marginTop: '12px', background: 'transparent', border: '1px solid var(--border)', color: 'var(--text-secondary)', borderRadius: '8px', padding: '8px 18px', cursor: 'pointer', fontSize: '13px' }}
                >
                  Create your first Purchase Order
                </button>
              )
            )}
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table className="erp-table">
              <thead>
                <tr>
                  <th>Reference</th>
                  <th>Vendor</th>
                  <th>Origin</th>
                  <th>Order Date</th>
                  <th>Expected Delivery</th>
                  <th style={{ textAlign: 'right' }}>Total Cost</th>
                  <th>Status</th>
                  <th style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {orders.map((o) => (
                  <tr key={o.id}>
                    <td style={{ fontWeight: 600, color: '#FF540E' }}>{o.orderRef}</td>
                    <td>{o.vendorName}</td>
                    <td>
                      {o.isAutoGenerated ? (
                        <span style={{
                          display: 'inline-flex', alignItems: 'center', gap: '4px',
                          background: 'rgba(255, 84, 14, 0.08)', color: '#FF540E',
                          border: '1px solid rgba(255, 84, 14, 0.2)',
                          borderRadius: '20px', padding: '2px 8px', fontSize: '11px', fontWeight: 600,
                        }}>
                          <Zap size={11} strokeWidth={2.5} /> MTO
                        </span>
                      ) : (
                        <span style={{ color: 'var(--text-muted)', fontSize: '12px' }}>Manual</span>
                      )}
                    </td>
                    <td>{new Date(o.orderDate).toLocaleDateString()}</td>
                    <td>{o.expectedDeliveryDate ? new Date(o.expectedDeliveryDate).toLocaleDateString() : '—'}</td>
                    <td style={{ textAlign: 'right', fontWeight: 600 }}>
                      ₹{(o.totalCost || 0).toFixed(2)}
                    </td>
                    <td><StatusBadge status={o.status} /></td>
                    <td style={{ textAlign: 'right' }}>
                      <button
                        onClick={() => navigate(`/purchase/${o.id}`)}
                        style={{
                          background: 'rgba(255,255,255,0.05)',
                          border: '1px solid var(--border)',
                          color: 'var(--text-primary)',
                          cursor: 'pointer',
                          padding: '4px 12px',
                          borderRadius: '6px',
                          fontSize: '12px',
                        }}
                      >
                        View
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {pagination && (
              <Pagination
                currentPage={pagination.currentPage}
                totalPages={pagination.totalPages}
                totalItems={pagination.totalItems}
                limit={pagination.limit}
                onPageChange={handlePageChange}
              />
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default PurchaseListPage;
